name: cicd-pipeline-acl

on:
  push:
    paths:
      - '*'
      - '.github/*'
      - '.github/workflows/cicd-pipeline-acl.yml'
      - '.husky/**'
      - 'cicd-pipeline-acl/**'


defaults:
  run: 
    working-directory: cicd-pipeline-acl

jobs:
  validation:
    name: 'validation'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'aws: configure'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CICD_PIPELINE_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: 'tf: setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'tf: format'
        id: fmt
        run: terraform fmt -check -recursive

      - name: 'tf: init'
        id: init
        run: terraform init

      - name: 'tf: validate'
        id: validate
        run: terraform validate





  